### ISSUE TITLE
 How this situation is resolved

### ISSUE THREAD

**Issue by slcns11212** [Antoniofo/AudioPlayer#5]
I'm having this kind of problem while using this plugin, who can help me
![Uploading CF32A41B3F72E47837141C4C8EAAE0A1.png…]()

**Comment by Antoniofo** [comment]
hi i can't see the image you send

**Comment by slcns11212** [comment]
AudioPlayer pilay sep ne.ogg
[A] [] Command execution failed! Error: System.MissingMethodException: Method not found: void
Exiled.API. Features.Log. Debug (string)
at AudioPlayer PlaySound.ExecuteParent (System. ArraySegment'1 [T] arguments,
CommandSystem. CommandSender sender, System. String& response) [0x000ff] in
<69deea05333f41b9b028d49426abd7bb> : 0
at ParentCommand. Execute (System. ArraySegment 1 [T] arguments, CommandSystem. ICommandSender
sender, System. String& response) [0x00049] in < 78fec8806b344fa98d415c3963591 fbd> :0
at (wrapper dynamic-method)
RemoteAdmin. CommandProcessor.RemoteAdmin.CommandProcessor.ProcessQuery_Patch0(string, CommandSende
r )

**Comment by Antoniofo** [comment]
what version of exiled are you using ?

**Comment by slcns11212** [comment]
8.9.11

**Comment by Antoniofo** [comment]
This plugin has been made for Exiled 8.11.0 from EXILED OFFICIAL not the Exiled Reboot (the one your using)
And i believe that there is a method that has been removed in the Exiled reboot which is still in Exiled OFFICIAL thats why you have this error

**Comment by Antoniofo** [comment]
i would recommend using this version of Exiled
https://github.com/ExMod-Team/EXILED

**Comment by slcns11212** [comment]
After installing it, there is a situation that it can run but cannot play audio.,Can you tell me what to do?,Thank you.

**Comment by Antoniofo** [comment]
does your audio file is in .ogg format with mono and 48000 sample rate located in the Exiled/Configs/audio folder ?

**Comment by slcns11212** [comment]
Appears to be a two-channel audio I'll try to  new an ogg

**Comment by Antoniofo** [comment]
ok i you found any error running the command send it here i'll be much simpler for me to see whats wrong

**Comment by slcns11212** [comment]
Problem solved, thank you very much for your help to me, thank you

**Comment by Antoniofo** [comment]
your welcome

**Comment by slcns11212** [comment]
Can you make an audio player for version 8.9.11? Because my auto events (minigame) plugin doesn't support exiled for 8.11.0

**Comment by Antoniofo** [comment]
i'll try to make it work with 8.9.11

**Comment by Antoniofo** [comment]
ok i've tested it on Exiled 8.9.11
https://github.com/Antoniofo/AudioPlayer/releases/tag/v2.0.1
here you go make sure you take the Exiled Reboot version only

**Comment by slcns11212** [comment]
thanks
